
server:
  port: 13000
spring:
  application:
    name: eureka-server

#eureka??
eureka:
  client:
    register-with-eureka: false #????????eureka ???????true?.
    fetch-registry: false #?????????????????????true?.
    service-url:
      defaultZone: http://127.0.0.1:13000/eureka
  server:
    enable-self-preservation: false #????????
