
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elme
    username: root
    password: root
  application:
    name: user-server

server:
  port: 10100

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    edu.ynu: debug
    root: info
  config: classpath:logging-config.xml
  file:
    name: ${logging.file.path}/${spring.application.name}.log
    path: logs
