
server:
  port: 14000
spring:
  application:
    name: gateway-server
  cloud:
    sentinel:
      transport:
        dashboard: localhost:9090
    gateway:
      globalcors: # ???????
        add-to-simple-url-handler-mapping: true # ??options???????
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*" # ????????????
            allowCredentials: true # ??????cookie
            maxAge: 360000 # ??????????
      routes: #????
        - id: userServer
          uri: lb://user-server
          predicates:
            - Path=/user/*/**
        - id: foodServer
          uri: lb://food-server
          predicates:
            - Path=/food/*/**
        - id: businessServer
          uri: lb://business-server
          predicates:
            - Path=/business/*/**
        - id: cartServer
          uri: lb://cart-server
          predicates:
            - Path=/cart/*/**
        - id: deliveryaddressServer
          uri: lb://deliveryaddress-server
          predicates:
            - Path=/deliveryaddress/*/**
        - id: orderServer
          uri: lb://order-server
          predicates:
            - Path=/order/*/**

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:13000/eureka
  instance:
    prefer-ip-address: true #??ip???Eureka??
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #????????ID
    lease-renewal-interval-in-seconds: 5 #??????
    lease-expiration-duration-in-seconds: 15 #??????







